# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AurNote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!

  # Pods for AurNote
  pod 'AWSS3'
  pod 'AWSCognito'
  pod 'GoogleSignIn'
  pod 'WeScan', '>= 0.9'
  pod 'CropViewController'
  pod 'Firebase/MLVisionTextModel'
  pod 'SendGrid-Swift'
  pod 'Hero'
end
